# tests/agents/researcherA/test_integrated_research_pipeline.py

import pytest
from src.agents.researcherA.state import ResearcherALocalState
from src.agents.researcherA.nodes.integration_prob import integration_prob_node
from src.agents.researcherA.nodes.enrichment import technical_enrichment_node
from src.agents.researcherA.nodes.voice import voice_profiling_node
from src.agents.researcherA.nodes.strategy import campaign_strategy_node

def test_integrated_discovery_and_enrichment_pipeline():
    """
    INTEGRATION TEST: Complete 4-Node Research Pipeline Handshake validation.
    Validates data generation from discovery up to final campaign strategy.
    """
    # 1. Arrange: Baseline state
    state: ResearcherALocalState = {
        "macro_trigger": "Modern cloud infrastructure technical debt and API failures",
        "executed_queries": [],
        "raw_scraped_artifacts": [],
        "synthesized_trends": [],
        "selected_trend": None,
        "enriched_context": None,
        "voice_guidelines": None,
        "campaign_strategy": None
    }
    
    print("\n\n📡 [STEP 1] Executing Node 1 (The Radar Layer)...")
    node_1_updates = integration_prob_node(state)
    state.update(node_1_updates)
    
    assert len(state["synthesized_trends"]) > 0
    target_trend_title = state["synthesized_trends"][0]["thematic_title"]
    print(f"✅ Node 1 successfully discovered trend pattern: '{target_trend_title}'")
    
    print("\n⛏️ [STEP 2] Pipeline Handshake: Executing Node 2 (The Excavator)...")
    node_2_updates = technical_enrichment_node(state)
    state.update(node_2_updates)
    assert state["enriched_context"] is not None
    
    print("\n🎭 [STEP 3] Running Node 3 (The Sculptor/Voice Guardrails)...")
    node_3_updates = voice_profiling_node(state)
    state.update(node_3_updates)
    assert state["voice_guidelines"] is not None
    
    print("\n♟️ [STEP 4] Running Node 4 (The Master Content Strategist)...")
    node_4_updates = campaign_strategy_node(state)
    state.update(node_4_updates)
    
    # Assert Campaign Strategy exists
    assert state["campaign_strategy"] is not None, "Pipeline Error: Node 4 failed to output strategy schema."
    assert "master_campaign_angle" in state["campaign_strategy"], "Pipeline Error: Strategy payload is malformed."
    
    # Visualizing final asset fuel
    print("\n" + "="*80)
    print("♟️ [CAMPAIGN STRATEGY GENERATED BY NODE 4] ♟️")
    print("="*80)
    print(f"Master Angle  : {state['campaign_strategy']['master_campaign_angle']}\n")
    print("Narrative Pillars:")
    for idx, pillar in enumerate(state['campaign_strategy']['key_narrative_pillars'], 1):
        print(f"  {idx}. {pillar}")
    print("\nPlatform Execution Maps:")
    for platform, data in state['campaign_strategy']['platform_blueprints'].items():
        print(f"  🔹 {platform.upper()}:")
        print(f"     Focus    -> {data['format_focus']}")
        print(f"     Argument -> {data['core_argument']}")
    print("="*80 + "\n")
    
    print("🟩 [FULL 4-NODE RESEARCH ENGINE COMPLETELY VALIDATED]")